### ISSUE TITLE
Support for npm3+

### ISSUE THREAD

**Issue by Crispy1975** [feross/zelda#12]
We love Zelda, great tool that eases a lot of pain. Are there plans to support the new npm3 flat format?

**Comment by feross** [comment]
Yeah, I'd love to support npm3 but haven't had time to do that yet. In the meantime, PR welcome!

**Comment by feross** [comment]
Working on this right now -- should be done soon.

**Comment by Crispy1975** [comment]
@feross awesome! If you need us to test then we are happy to do that. Thanks for your efforts!

**Comment by feross** [comment]
Released as 3.0.0.

**Comment by Crispy1975** [comment]
Quickest release ever! Will test this out, thanks!

**Comment by Crispy1975** [comment]
To be clear this release will only work with npm3+?

**Comment by feross** [comment]
I haven't tested it with npm2, but I see no reason why this approach wouldn't work there too.
