### ISSUE TITLE
Optionally use yarn?

### ISSUE THREAD

**Issue by andywer** [feross/zelda#16]
Hey @feross.
I like the idea of zelda :) Maybe @lerna could even use it as part of `lerna bootstrap`.

Since yarn is so hip, since it is much faster than the normal `npm install` it might be a good idea to provide yarn support.

Cheers!

**Comment by feross** [comment]
That's a neat idea. I'd rather stick with the tried-and-true at the moment. But if you want to fork this and add yarn support, go for it!

**Comment by idanilt** [comment]
#23
