### ISSUE TITLE
Additional command support

### ISSUE THREAD

**Issue by alasdairhurst** [feross/zelda#19]
If I can actually get this working for my use case if #18 is fixed, I would also like the ability to run additional commands alongside npm install for my modules. My modules all use babel and need to be transpiled before they can be used. I would like the ability to ```npm run build``` after ```npm install``` in my linked modules.

Either a config or command passed to zelda would be nice.
```
>git clone A
>git clone x
>cd A
> zelda npm run build
[zelda] linking x
[zelda] npm install x
[zelda] npm run build x
[zelda] npm install A
```

**Comment by feross** [comment]
Sorry, this feels like scope creep to me.

You can actually already accomplish what you want with a postinstall script. Just add this to package.json:

```
{
  "build": "...",
  "postinstall": "npm run build"
}
```
